### ISSUE TITLE
Test Landing Page

### ISSUE THREAD

**Issue by boehmbe** [leasyro/aloha-landing#1]
As a potential customer, I would like to see a test landing page so that I know whether I can imagine working together.

- Customer Website: https://www.alohaliving.de
- Sample Content: [Ratgeber Immoblie geerbt.pdf](https://github.com/leasyro/aloha-landing/files/15061835/Ratgeber.Immoblie.geerbt.pdf)
- Reference page: https://www.jacasa.de/ratgeber/erbschaft/erbengemeinschaft
- Fonts: Cairo / Montserat (for Headlines)
- Logo: ![aloha](https://github.com/leasyro/aloha-landing/assets/82403211/c064ec91-c849-4379-8424-6ea66019cf5a)
- Colors: ![aloha-colors](https://github.com/leasyro/aloha-landing/assets/82403211/0b1dbcb2-6ba9-4825-b1ce-4404ed9a8417)

AC
- [x] next.js project hosted on vercel under https://aloha-landing.dev.xberg.dev
- [x] basic landing page structure with call to action created
- [x] landing page contains pdf contents

**Comment by MartinBehrmann06** [comment]
@boehmbe guck mal wie du es findest, hab nicht alles übernommen. Sieht aber trotzdem nach viel text aus.

**Comment by boehmbe** [comment]
@MartinBehrmann06 
Ich finds mega, danke dir!

Hab noch deren favicon und Schriftart hinzugefügt und nen PR gemacht, damit wir nen Vercel Preview Deployment haben: 
https://github.com/leasyro/aloha-landing/pull/2 

Kann erstmal so bleiben, ich schicks dem Kunden und geb dir dann Bescheid, was sie sagen.
